from colorama import Back, Fore

BOARD_HEIGHT = int(20)
BOARD_WIDTH = int(40)
BLOCK_WIDTH = int(3)
INIT_PADDLE_LENGTH = int(20)
PADDLE_OUTPUT = Back.WHITE + Fore.BLACK + "==="
SLEEPTIME = 1

PROB_PADDLE_EXPAND = 0.1
PROB_PADDLE_SHRINK = 0.1
PROB_PADDLE_GRAB = 0.1
PROB_BALL_MULTIPLIER = 0.1
PROB_BALL_FAST = 0.1
PROB_BALL_THRU = 0.1

MIN_PADDLE_LENGTH = 2
MAX_PADDLE_LENGTH = 10

MAX_BALL_VELOCITY = 5
